n1 = input('digite um numero: ')
n2 = input('digite outro numero: ')
soma = int(n1 + n2)
print('A soma de {} com {} é {}'.format(n1, n2, soma))
print('O tipo da soma é {}'.format(type(soma)))

n3 = input('digite um numero: ')
n4 = input('digite outro numero: ')
soma2 = float(n3 + n4)
print('A soma2 de {} com {} é {}'.format(n3, n4, soma2))
print('O tipo de soma2 é {}'.format(type(soma2)))
print('n1 é número? {}'.format(n1.isnumeric()))
print('n2 é texto? {}'.format(n2.isalpha()))
print('n3 é alfanumérico? {}'.format(n3.isalpha()))
print('n4 é flutuante? {}'.format(n4.isdecimal()))