nome = str(input('Digite seu nome completo: ')).strip()
print('Analisando seu nome...\n')
print('Seu nome em maiúsculas é: {}'.format(nome.upper()))
print('Seu nome em minúsculas é: {}'.format(nome.lower()))
nome_sem_espacos = nome.replace(' ', '')
print('Seu nome ao todo em {} letras, sem espaços.'.format(len(nome_sem_espacos)))
print('Seu nome ao todo em {} letras, com espaços.'.format(len(nome)))
partes = nome.split()
print('Seu primeiro nome é {} e ele tem {} letras.'.format(partes[0], len(partes[0])))
print('Seu primeiro nome tem {} letras.'.format(nome.find(' ')))
